export const Fields = [ 
    'pt08Co', 
    'nmhc',  
    'c6h6',  
    'pt08Nmhc',   
    'nox',  
    'pt08Nox',   
    'no2',   
    'pt08No2',  
    'pt08O3',     
    't',   
    'rh',
    'ah',  
    'weekday',  
    'hour']